package be.billsbillsbills.entities;

public enum Category {
	RESTAURANT, RELATIEGESCHENK, KANTOORMATERIAAL, UTILITY, TRANSPORT, VARIA, HUISVESTING, SOCIALE_BIJDRAGEN, VERZEKERING, PENSIOEN  

}
